### ISSUE TITLE
Is it possible to initially show a custom keyboard without having to toggle?

### ISSUE THREAD

**Issue by deantes** [wix-incubator/react-native-keyboard-input#46]

**Comment by gerbyzation** [comment]
got the same question, would be great to show a custom keyboard as soon as it focusses on a text element

**Comment by swaroopa94** [comment]
@deantes @gerbyzation  Hi did you found solution I just kept the custom keyboard in onFocus method. Its Working fine for first time but second time when click on textinputs it shows the soft keyboard first and then custom keyboard.

How to solve this I need this functionality urgently

**Comment by gerbyzation** [comment]
On Android it seems to work OK to open it straight away, so we're using a custom keyboard on android and native one on iOS (else it would still flash the native keyboard first).

**Comment by swaroopa94** [comment]
@gerbyzation Yes there is any other solution for displaying custom keyboard without getting the soft keyboard at flash

**Comment by gerbyzation** [comment]
@swaroopa94 If I'd know I'd be using it instead of falling back on native keyboard. if you're desparate you could always build a separate keyboard component avoiding the build-in keyboard module (something like http://johncblandii.com/2017/05/react-native-pin-entry-view-with-a-custom-keyboard.html)

**Comment by swaroopa94** [comment]
@gerbyzation  Yes I referred this but if I do like this the cursor in the textInput does not appear and user cannot modify the text in it.

**Comment by 3luyka** [comment]
any updates?
